# Do NOT update manually; changes here will be overwritten by Copier
_commit: 1588e18
_src_path: https://github.com/grap/oca-addons-repo-template-v16
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 16.0
org_name: GRAP
org_slug: grap
rebel_module_groups: []
repo_description: ' This project aim to deal with modules related to manage CAE in
    Odoo.

    More information about CAE [FR]

    - https://fr.wikipedia.org/wiki/Coopérative_d''activités_et_d''emploi

    - http://www.cooperer.coop/

    - http://www.copea.fr/'
repo_name: Odoo Modules for CAE (Cooperative d'Activité et d'Emploi)
repo_slug: odoo-addons-cae
repo_website: https://github.com/grap/odoo-addons-cae
use_pyproject_toml: false
use_ruff: true
