# Do NOT update manually; changes here will be overwritten by Copier
_commit: 5a39237
_src_path: https://github.com/grap/oca-addons-repo-template-new.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_real_version: 12.0
odoo_version: 16.0
org_name: GRAP
org_slug: grap
rebel_module_groups: []
repo_description: ' This project aim to deal with modules related to manage CAE in
    Odoo.

    More information about CAE [FR]

    - https://fr.wikipedia.org/wiki/Coopérative_d''activités_et_d''emploi

    - http://www.cooperer.coop/

    - http://www.copea.fr/'
repo_name: Odoo Modules for CAE (Cooperative d'Activité et d'Emploi)
repo_slug: odoo-addons-cae
repo_website: https://github.com/grap/odoo-addons-cae
travis_apt_packages: []
travis_apt_sources: []

